# Generated by Django 3.2.18 on 2024-03-13 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwtauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='workouts',
            name='instructions',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='workouts',
            name='recomended_rep',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='workouts',
            name='recomended_sets',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workouts',
            name='target_muscles',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='jwtauth.muscles'),
        ),
    ]
