# Generated by Django 5.0.3 on 2024-03-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('workouts', models.CharField(default='', max_length=500)),
                ('duration', models.DateField()),
                ('rep_in_day', models.IntegerField(default=1)),
            ],
        ),
    ]
