# Generated by Django 5.0.3 on 2024-03-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_workoutplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='owner',
            field=models.IntegerField(default=0),
        ),
    ]
